### ISSUE TITLE
It's unclear that primitive type "uri" enclose URNs (not only URLs)

### ISSUE THREAD

**Issue by Kroisse** [nirum-lang/nirum#126]
Currently, Nirum specification doesn't clarify their implementors to treat "uri" be a union of [Uniform Resource Locator][1] and [Uniform Resource Name][2], or accept URL only and reject URN. Because URN is used rarely in practice, most of Nirum users might want to exclude URN during serialization and deserialization. Furthermore, most of programming languages don't have URN datatype in their standard library. It makes hard to implement the runtime for them.

[1]: https://en.wikipedia.org/wiki/Uniform_Resource_Locator
[2]: https://en.wikipedia.org/wiki/Uniform_Resource_Name

**Comment by dahlia** [comment]
I suggest to rename `uri` to `url`.

**Comment by dahlia** [comment]
The compiler 0.4 will be released with a new type name `url` and deprecated `uri` (which is aliased to `url`).

In the next minor release we need to obsolete `uri`.

**Comment by dahlia** [comment]
PR #281 implemented it.
