### ISSUE TITLE
OpenGraph metadata on generated docs

### ISSUE THREAD

**Issue by dahlia** [nirum-lang/nirum#283]
[Open Graph] is the most widely-used, and de facto standard metadata specification for the Web.  Facebook, Twitter, Slack, etc. can recognize it.  These can be also good for SEO of the generated docs.

Read [A Guide to Sharing for Webmasters][1] as well.

[Open Graph]: http://ogp.me/
[1]: https://developers.facebook.com/docs/sharing/webmasters/

**Comment by Ephemera** [comment]
I will fix it.

**Comment by dahlia** [comment]
PR #305 implemented it.
