### ISSUE TITLE
TOML reading should be independent from locale settings

### ISSUE THREAD

**Issue by dahlia** [nirum-lang/nirum#290]
According to TOML specification:

> A TOML file must be a valid UTF-8 encoded Unicode document.

The current implementation implicitly decodes the bytes from a *package.toml* file according to the system locale settings (e.g., `LOCALE`, `LC_ALL`).

```
Scan error: ./package.toml: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by AlanSynn** [comment]
on going

**Comment by AlanSynn** [comment]
Couldn't get approaches to set LOCALEs on mac. (e.g. Latin1, EUC-KR, CP949)
If you want to make a further progress, then set a docker environment for Linux.
